volumes:
  ddb_data:
services:
  dynamodb-local:
    platform: linux/amd64
    user: root
    network_mode: host
    command: "java -Djava.net.preferIPv4Stack=true -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data -port 8005"
    build:
      dockerfile: ../ddb-local.Dockerfile
    container_name: dynamodb-local
    volumes:
      - ddb_data:/home/dynamodblocal/data
    healthcheck:
      test: ["CMD-SHELL", "curl -Is -o /dev/null localhost:8005 || exit 1"]
      interval: 1m
      timeout: 30s
      retries: 2
      start_period: 30s
      start_interval: 5s
  datomic-ttor:
    depends_on:
      dynamodb-local:
        condition: service_healthy
    network_mode: host
    build:
      dockerfile: ../datomic-pro.Dockerfile
      args:
        DATOMIC_VERSION: 1.0.7075
    container_name: datomic-ttor
    environment:
      AWS_ACCESS_KEY_ID: DUMMYKEY
      AWS_SECRET_ACCESS_KEY: DUMMYSECRET
      AWS_REGION: us-east-1
    healthcheck:
      test: ["CMD", "curl", "-fs", "localhost:9999/health"]
      interval: 1m
      timeout: 30s
      retries: 2
      start_period: 1m30s
    volumes:
      - ${PWD}/files/ddb-local-transactor.properties:/opt/datomic-pro/transactor.properties
    # command: "tail -f bin/datomic"
    command: bash -c "
      ./bin/datomic ensure-transactor transactor.properties transactor.properties &&
      ./bin/transactor -Djava.net.preferIPv4Stack=true -Xms4g -Xmx4g -XX:+UseG1GC transactor.properties"